apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/scheme":"internet-facing","alb.ingress.kubernetes.io/target-type":"ip"},"name":"frontend-proxy","namespace":"default"},"spec":{"ingressClassName":"alb","rules":[{"host":"example.com","http":{"paths":[{"backend":{"service":{"name":"opentelemetry-demo-frontendproxy","port":{"number":8080}}},"path":"/","pathType":"Prefix"}]}}]}}
    creationTimestamp: "2026-01-03T05:52:07Z"
    finalizers:
    - ingress.k8s.aws/resources
    generation: 1
    name: frontend-proxy
    namespace: default
    resourceVersion: "2763158"
    uid: 5a18ce21-494e-4074-8c77-ef060a48e0e9
  spec:
    ingressClassName: alb
    rules:
    - host: example.com
      http:
        paths:
        - backend:
            service:
              name: opentelemetry-demo-frontendproxy
              port:
                number: 8080
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - hostname: k8s-default-frontend-0688e8f0fd-1599926159.us-east-1.elb.amazonaws.com
        ports:
        - port: 80
          protocol: ""
kind: List
metadata:
  resourceVersion: ""
