apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIJ5xPFJdwhCUwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNTEyMjQwNTM1MDlaFw0zNTEyMjIwNTQwMDlaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQCvgesRZkZ8rEduxXpFVE3euk5OVX9Q04kt+1uNULXOvCNezTVBo2zv5sMJ
      33QtVJ8M7HtPGRWHeQumpsh2YLlX+UU4pFB3DkTOjzm74J+jBwsbCyFeVykqFz0l
      CrG1prX/T8bQeHzoMfsyOgefMfOIHKxG29CSDOu8qA1BUer1x6StdiMkVUCcdA4O
      oIBqD4lwJclmES87CcxA74QyeUSmECcgMc0vevPfnftxd5P+Q7xk7VEQdDc8LA3l
      mow76O9qPvpwFwZgJfF52I/uswQDcUucQSubr0GQBy2OVkx1Ltpgn/+MZZ+5f7rt
      RV/dktTYNq5yZ4fp5T4VjF5Kh8ubAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQUv/vYvYtmSOikkFH+P1MB91HFsDAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAHRuB0/A//
      Oux35ukE0pgQsMVd9P26i3vHQBBNCVtHjKwb8OdiW6/IF2hniB7sVnsjun/b6P2o
      funE2iDxLLkcCsPw0hwoThMU9scDFH3N87Qt/FsHLR2hl35047YZOxAhte6ET6q0
      3pjW9iVztGYtke9qPMzanXuq4jpuPIBXCGLueLEyPee1+w+MHa+6ufuO9EZ45auJ
      LN71dSwZgY61/6cTPDFfm/Imj7/UZ8p9g0EdVI0TB+vdT1+OXx04m4Zc0vr30Peh
      IAc3yJVqixfVbw1B2+1j1EPzWwZ2AN/04TU9jW0dg5o/+sAsA8iUA8T8Bf5d/BLK
      eghQoFInrs9t
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-12-24T05:40:48Z"
    name: kube-root-ca.crt
    namespace: default
    resourceVersion: "376"
    uid: 984cca34-610f-4392-bcf8-386037b1d92d
- apiVersion: v1
  data:
    demo.flagd.json: |
      {
        "$schema": "https://flagd.dev/schema/v0/flags.json",
        "flags": {
          "productCatalogFailure": {
            "description": "Fail product catalog service on a specific product",
            "state": "ENABLED",
            "variants": {
              "on": true,
              "off": false
            },
            "defaultVariant": "off"
          },
          "recommendationServiceCacheFailure": {
            "description": "Fail recommendation service cache",
            "state": "ENABLED",
            "variants": {
              "on": true,
              "off": false
            },
            "defaultVariant": "off"
          },
          "adServiceManualGc": {
            "description": "Triggers full manual garbage collections in the ad service",
            "state": "ENABLED",
            "variants": {
              "on": true,
              "off": false
            },
            "defaultVariant": "off"
          },
          "adServiceHighCpu": {
            "description": "Triggers high cpu load in the ad service",
            "state": "ENABLED",
            "variants": {
              "on": true,
              "off": false
            },
            "defaultVariant": "off"
          },
          "adServiceFailure": {
            "description": "Fail ad service",
            "state": "ENABLED",
            "variants": {
              "on": true,
              "off": false
            },
            "defaultVariant": "off"
          },
          "kafkaQueueProblems": {
            "description": "Overloads Kafka queue while simultaneously introducing a consumer side delay leading to a lag spike",
            "state": "ENABLED",
            "variants": {
              "on": 100,
              "off": 0
            },
            "defaultVariant": "off"
          },
          "cartServiceFailure": {
            "description": "Fail cart service",
            "state": "ENABLED",
            "variants": {
              "on": true,
              "off": false
            },
            "defaultVariant": "off"
          },
          "paymentServiceFailure": {
            "description": "Fail payment service charge requests",
            "state": "ENABLED",
            "variants": {
              "on": true,
              "off": false
            },
            "defaultVariant": "off"
          },
          "paymentServiceUnreachable": {
            "description": "Payment service is unavailable",
            "state": "ENABLED",
            "variants": {
              "on": true,
              "off": false
            },
            "defaultVariant": "off"
          },
          "loadgeneratorFloodHomepage": {
            "description": "Flood the frontend with a large amount of requests.",
            "state": "ENABLED",
            "variants": {
              "on": 100,
              "off": 0
            },
            "defaultVariant": "off"
          },
          "imageSlowLoad": {
            "description": "slow loading images in the frontend",
            "state": "ENABLED",
            "variants": {
              "10sec": 10000,
              "5sec": 5000,
              "off": 0
            },
            "defaultVariant": "off"
          }
        }
      }
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"demo.flagd.json":"{\n  \"$schema\": \"https://flagd.dev/schema/v0/flags.json\",\n  \"flags\": {\n    \"productCatalogFailure\": {\n      \"description\": \"Fail product catalog service on a specific product\",\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": true,\n        \"off\": false\n      },\n      \"defaultVariant\": \"off\"\n    },\n    \"recommendationServiceCacheFailure\": {\n      \"description\": \"Fail recommendation service cache\",\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": true,\n        \"off\": false\n      },\n      \"defaultVariant\": \"off\"\n    },\n    \"adServiceManualGc\": {\n      \"description\": \"Triggers full manual garbage collections in the ad service\",\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": true,\n        \"off\": false\n      },\n      \"defaultVariant\": \"off\"\n    },\n    \"adServiceHighCpu\": {\n      \"description\": \"Triggers high cpu load in the ad service\",\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": true,\n        \"off\": false\n      },\n      \"defaultVariant\": \"off\"\n    },\n    \"adServiceFailure\": {\n      \"description\": \"Fail ad service\",\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": true,\n        \"off\": false\n      },\n      \"defaultVariant\": \"off\"\n    },\n    \"kafkaQueueProblems\": {\n      \"description\": \"Overloads Kafka queue while simultaneously introducing a consumer side delay leading to a lag spike\",\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": 100,\n        \"off\": 0\n      },\n      \"defaultVariant\": \"off\"\n    },\n    \"cartServiceFailure\": {\n      \"description\": \"Fail cart service\",\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": true,\n        \"off\": false\n      },\n      \"defaultVariant\": \"off\"\n    },\n    \"paymentServiceFailure\": {\n      \"description\": \"Fail payment service charge requests\",\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": true,\n        \"off\": false\n      },\n      \"defaultVariant\": \"off\"\n    },\n    \"paymentServiceUnreachable\": {\n      \"description\": \"Payment service is unavailable\",\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": true,\n        \"off\": false\n      },\n      \"defaultVariant\": \"off\"\n    },\n    \"loadgeneratorFloodHomepage\": {\n      \"description\": \"Flood the frontend with a large amount of requests.\",\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"on\": 100,\n        \"off\": 0\n      },\n      \"defaultVariant\": \"off\"\n    },\n    \"imageSlowLoad\": {\n      \"description\": \"slow loading images in the frontend\",\n      \"state\": \"ENABLED\",\n      \"variants\": {\n        \"10sec\": 10000,\n        \"5sec\": 5000,\n        \"off\": 0\n      },\n      \"defaultVariant\": \"off\"\n    }\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"opentelemetry-demo","app.kubernetes.io/name":"opentelemetry-demo","app.kubernetes.io/part-of":"opentelemetry-demo","app.kubernetes.io/version":"1.12.0","opentelemetry.io/name":"opentelemetry-demo"},"name":"opentelemetry-demo-flagd-config","namespace":"default"}}
    creationTimestamp: "2025-12-31T05:58:08Z"
    labels:
      app.kubernetes.io/instance: opentelemetry-demo
      app.kubernetes.io/name: opentelemetry-demo
      app.kubernetes.io/part-of: opentelemetry-demo
      app.kubernetes.io/version: 1.12.0
      opentelemetry.io/name: opentelemetry-demo
    name: opentelemetry-demo-flagd-config
    namespace: default
    resourceVersion: "1921817"
    uid: a267ef5e-7852-450b-a407-0eb7f64ce7c6
kind: List
metadata:
  resourceVersion: ""
